/*
 * Copyright 2026 Shekhar Maheswari.
 * All rights reserved.
 *
 * This source code is private and proprietary until an explicit open-source
 * license is published with this project.
 */
package io.relay.reasoning;

import java.time.Duration;

/**
 * Captures the outcome and telemetry of a single step's execution in a Chain-of-Thought pipeline.
 *
 * @param stepName the name of the executed step
 * @param input    the input text supplied to the step
 * @param output   the output text generated by the step
 * @param logs     any logging or audit details produced during execution
 * @param success  indicates if the step executed successfully; if false, the pipeline halts
 * @param latency  the execution duration of this step
 */
public record StepResult(
        String stepName,
        String input,
        String output,
        String logs,
        boolean success,
        Duration latency
) {
}
