/*
 * Copyright 2026 Shekhar Maheswari.
 * All rights reserved.
 *
 * This source code is private and proprietary until an explicit open-source
 * license is published with this project.
 */
package io.relay.tool.dynamic;

import java.util.Map;
import java.util.Objects;

import org.springframework.ai.tool.ToolCallback;
import org.springframework.ai.tool.definition.ToolDefinition;
import org.springframework.http.MediaType;
import org.jspecify.annotations.NonNull;
import org.springframework.web.client.RestClient;
import org.springframework.web.util.UriComponentsBuilder;

import com.fasterxml.jackson.databind.ObjectMapper;

import lombok.Builder;
import lombok.extern.slf4j.Slf4j;

/**
 * A universal HTTP/REST dynamic connector implementing Spring AI's {@link ToolCallback}.
 *
 * <p>Exposes any HTTP endpoint directly to the LLM as an active tool. It parses the JSON input
 * generated by the LLM and dispatches it securely using either query parameters (for GET)
 * or the request body (for POST, PUT, etc.).
 */
@Slf4j
public class DynamicRestTool implements ToolCallback {

    private final String name;
    private final String description;
    private final String targetUrl;
    private final String method;
    private final Map<String, String> staticHeaders;
    private final String inputSchema;
    private final RestClient restClient;
    private final ObjectMapper objectMapper;

    @Builder
    public DynamicRestTool(
            final String name,
            final String description,
            final String targetUrl,
            final String method,
            final Map<String, String> staticHeaders,
            final String inputSchema,
            final ObjectMapper objectMapper) {
        this.name = Objects.requireNonNull(name, "Name must not be null");
        this.description = Objects.requireNonNull(description, "Description must not be null");
        this.targetUrl = Objects.requireNonNull(targetUrl, "Target URL must not be null");
        this.method = method != null ? method.trim().toUpperCase() : "POST";
        this.staticHeaders = staticHeaders != null ? staticHeaders : Map.of();
        this.inputSchema = inputSchema != null ? inputSchema : "{\"type\":\"object\",\"properties\":{}}";
        this.objectMapper = objectMapper != null ? objectMapper : new ObjectMapper();
        
        // Build rest client
        this.restClient = RestClient.builder().build();
    }

    @Override
    public @NonNull ToolDefinition getToolDefinition() {
        return ToolDefinition.builder()
                .name(name)
                .description(description)
                .inputSchema(inputSchema)
                .build();
    }

    @Override
    public @NonNull String call(final @NonNull String toolInput) {
        log.info("Executing dynamic connector tool={} targetUrl={} method={}", name, targetUrl, method);
        try {
            if ("GET".equals(method)) {
                // Parse input to attach query params
                UriComponentsBuilder uriBuilder = UriComponentsBuilder.fromUriString(targetUrl);
                try {
                    @SuppressWarnings("unchecked")
                    Map<String, Object> params = objectMapper.readValue(toolInput, Map.class);
                    if (params != null) {
                        params.forEach((key, value) -> {
                            if (value != null) {
                                uriBuilder.queryParam(key, value.toString());
                            }
                        });
                    }
                } catch (Exception ex) {
                    log.warn("Failed to parse tool input as JSON for GET query parameters: {}", ex.getMessage());
                }

                String finalUrl = uriBuilder.build().toUriString();
                log.debug("Dispatching GET request to: {}", finalUrl);

                return restClient.get()
                        .uri(finalUrl)
                        .headers(httpHeaders -> staticHeaders.forEach(httpHeaders::add))
                        .accept(MediaType.APPLICATION_JSON)
                        .retrieve()
                        .body(String.class);
            } else {
                // POST, PUT, etc.
                log.debug("Dispatching {} request to: {}", method, targetUrl);

                return restClient.method(org.springframework.http.HttpMethod.valueOf(method))
                        .uri(targetUrl)
                        .headers(httpHeaders -> staticHeaders.forEach(httpHeaders::add))
                        .contentType(MediaType.APPLICATION_JSON)
                        .body(toolInput)
                        .accept(MediaType.APPLICATION_JSON)
                        .retrieve()
                        .body(String.class);
            }
        } catch (Exception ex) {
            log.error("Dynamic REST connector tool={} failed execution: {}", name, ex.getMessage(), ex);
            return "{\"status\":\"error\",\"message\":\"" + ex.getMessage().replace("\"", "\\\"") + "\"}";
        }
    }
}
